apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ril-eks
    app.kubernetes.io/instance: ril-eks-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: ril-eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ril-eks
  template:
    metadata:
      labels:
        app: ril-eks
    spec:
      containers:
        - image: 962804699607.dkr.ecr.us-west-2.amazonaws.com/ril-ecr:latest
          imagePullPolicy: Always
          name: ril-react-app
          ports:
            - containerPort: 3000