apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ril-eks
    app.kubernetes.io/instance: ril-eks-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: ril-eks-deployment
spec:
  selector:
    app: ril-eks
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000